#!/bin/bash

yarn install
yarn build

#not really needed, unless something in here changes
#yarn build-container

docker stop boatfights

./src/server/create-container.sh $PWD $HOME/boats 80

docker start boatfights

