#!/bin/bash

npm install
npm build

#not really needed, unless something in here changes
#npm build-container

docker stop boatfights

./src/server/create-container.sh $PWD $HOME/boats 80

docker start boatfights

